"""role on Employee

Revision ID: 8f007f7f4727
Revises: 5d66f8d2b0a3
Create Date: 2023-07-20 16:15:25.834650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f007f7f4727'
down_revision = '5d66f8d2b0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
