"""is_active on Employee

Revision ID: b58f6b0fdeba
Revises: e5df222a2f78
Create Date: 2023-07-20 14:20:27.089588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58f6b0fdeba'
down_revision = 'e5df222a2f78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_employee', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_employee', 'is_active')
    # ### end Alembic commands ###
