"""init models

Revision ID: e5df222a2f78
Revises: 
Create Date: 2023-07-20 14:17:43.896791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5df222a2f78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_company_id'), 't_company', ['id'], unique=False)
    op.create_index(op.f('ix_t_company_name'), 't_company', ['name'], unique=False)
    op.create_table('t_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_role_id'), 't_role', ['id'], unique=False)
    op.create_index(op.f('ix_t_role_name'), 't_role', ['name'], unique=False)
    op.create_table('t_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['t_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_department_id'), 't_department', ['id'], unique=False)
    op.create_index(op.f('ix_t_department_name'), 't_department', ['name'], unique=False)
    op.create_table('t_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['t_department.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_employee_firstname'), 't_employee', ['firstname'], unique=False)
    op.create_index(op.f('ix_t_employee_id'), 't_employee', ['id'], unique=False)
    op.create_index(op.f('ix_t_employee_lastname'), 't_employee', ['lastname'], unique=False)
    op.create_index(op.f('ix_t_employee_title'), 't_employee', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_employee_title'), table_name='t_employee')
    op.drop_index(op.f('ix_t_employee_lastname'), table_name='t_employee')
    op.drop_index(op.f('ix_t_employee_id'), table_name='t_employee')
    op.drop_index(op.f('ix_t_employee_firstname'), table_name='t_employee')
    op.drop_table('t_employee')
    op.drop_index(op.f('ix_t_department_name'), table_name='t_department')
    op.drop_index(op.f('ix_t_department_id'), table_name='t_department')
    op.drop_table('t_department')
    op.drop_index(op.f('ix_t_role_name'), table_name='t_role')
    op.drop_index(op.f('ix_t_role_id'), table_name='t_role')
    op.drop_table('t_role')
    op.drop_index(op.f('ix_t_company_name'), table_name='t_company')
    op.drop_index(op.f('ix_t_company_id'), table_name='t_company')
    op.drop_table('t_company')
    # ### end Alembic commands ###
